#ifndef _CUST_PMIC_H_
#define _CUST_PMIC_H_

//#define MT6333_I2C_CHANNEL_CHANGED_0
//#define MT6333_I2C_CHANNEL_CHANGED_2

#define LOW_POWER_LIMIT_LEVEL_1 15
#define LOW_POWER_LIMIT_LEVEL_2 25

#endif /* _CUST_PMIC_H_ */ 
